### ISSUE TITLE
Error in CNN training file creation

### ISSUE THREAD

**Issue by stevexyz** [paintception/DeepChess#1]
I did some tests trying to replicate the process.
I did some minor correction (print parenthesis, xrange and tabs adjustment) to run in python3.
I stopped ad "FeatureDataset.py" that on all datasets was missing I think some layers. These are the errors reported with Open, Middle and End files:
- ValueError: cannot reshape array of size 788460 into shape (773,8,8,16)
- ValueError: cannot reshape array of size 444720 into shape (436,8,8,16)
- ValueError: cannot reshape array of size 106080 into shape (104,8,8,16)

Note that all the differences are exactly a multiple of four of the first dimension

Side note: BitmapDataset.py worked but example network is just CNN.

**Comment by paintception** [comment]
Hi thanks for your feedback!

So if I understood correctly you are unable to create the chess representation suitable for the CNN which should be trained with the "Features-Input"? My guess is that the input representation does not match with the tensor that the ANN expects, I will look at it asap!

You could also use the CNN network on the "Bitmap Input" by changing self.channels from 16 to 12,  does that work? If so it means that the error in the Features-Input is in the last 4 dimensions of the tensor and I would know where to look for the error.

**Comment by stevexyz** [comment]
This happened launching ExampleCNN.py "adapting" the input (12 channels and file renaming):

``
$ python3 ExampleCNN.py 
Using TensorFlow backend.
/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "ExampleCNN.py", line 100, in <module>
    ConvNet.main()	
  File "ExampleCNN.py", line 85, in main
    self.Labels = self.OneHotEncoding(self.Evaluations)
  File "ExampleCNN.py", line 42, in OneHotEncoding
    final_y = np_utils.to_categorical(encoded_y, self.classes)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/np_utils.py", line 29, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 68 is out of bounds for axis 1 with size 3
``

**Comment by paintception** [comment]
How many classes do you have in your labels file? It seems you are trying to create way too many one hot encoding matrices
